services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: cloudru-tz-backend
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./reports:/app/reports
      - ./runs:/app/runs
      - ./prompt_versions:/app/prompt_versions
      - ./rag_cache:/app/rag_cache

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: cloudru-tz-ui
    environment:
      BACKEND_API_URL: http://backend:8000
      OPENAI_API_BASE: ${OPENAI_API_BASE:-https://foundation-models.api.cloud.ru/v1}
      OPENAI_MODEL: ${OPENAI_MODEL:-openai/gpt-oss-120b}
      OPENAI_TEMPERATURE: ${OPENAI_TEMPERATURE:-0.05}
      MANAGED_RAG_URL: ${MANAGED_RAG_URL:-https://e424a162-618c-4862-b789-b089abd81b46.managed-rag.inference.cloud.ru/api/v2/retrieve_generate}
      MANAGED_RAG_KB_VERSION: ${MANAGED_RAG_KB_VERSION:-eb73eb63-ec91-47c9-851e-1c14949b7a14}
      MANAGED_RAG_RESULTS: ${MANAGED_RAG_RESULTS:-2}
      MANAGED_RAG_CONTEXT_CHUNKS: ${MANAGED_RAG_CONTEXT_CHUNKS:-3}
      MANAGED_RAG_MAX_TOKENS: ${MANAGED_RAG_MAX_TOKENS:-256}
      MANAGED_RAG_CONCURRENCY: ${MANAGED_RAG_CONCURRENCY:-4}
      MANAGED_RAG_CACHE_ENABLED: ${MANAGED_RAG_CACHE_ENABLED:-true}
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "8501:8501"
